<?xml version="1.0" encoding="utf-8"?><Database Name="OldersDB" Class="OldersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SHIMONSAMAY;Initial Catalog=OldersDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OldersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OldersTab" Member="OldersTabs">
    <Type Name="OldersTab">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>